// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xJd--odN53tnt7Q591nWN41PBau2hw4',
    appId: '1:332955303515:web:5caee4b0d772385572c97e',
    messagingSenderId: '332955303515',
    projectId: 'senario-dafa4',
    authDomain: 'senario-dafa4.firebaseapp.com',
    storageBucket: 'senario-dafa4.firebasestorage.app',
    measurementId: 'G-9GPDBEL087',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU_aje3cykS5V2OCT-jxnh-mOTds3jXRU',
    appId: '1:332955303515:android:f4900e79de6d03a072c97e',
    messagingSenderId: '332955303515',
    projectId: 'senario-dafa4',
    storageBucket: 'senario-dafa4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9m_UAZauDo8J10e7LrlziJfGuSXa1zI',
    appId: '1:332955303515:ios:9ddf33da4e6ca22572c97e',
    messagingSenderId: '332955303515',
    projectId: 'senario-dafa4',
    storageBucket: 'senario-dafa4.firebasestorage.app',
    iosBundleId: 'com.example.scenarioManagementToolForTesters',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9m_UAZauDo8J10e7LrlziJfGuSXa1zI',
    appId: '1:332955303515:ios:9ddf33da4e6ca22572c97e',
    messagingSenderId: '332955303515',
    projectId: 'senario-dafa4',
    storageBucket: 'senario-dafa4.firebasestorage.app',
    iosBundleId: 'com.example.scenarioManagementToolForTesters',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3xJd--odN53tnt7Q591nWN41PBau2hw4',
    appId: '1:332955303515:web:462423465396692d72c97e',
    messagingSenderId: '332955303515',
    projectId: 'senario-dafa4',
    authDomain: 'senario-dafa4.firebaseapp.com',
    storageBucket: 'senario-dafa4.firebasestorage.app',
    measurementId: 'G-RXN6X8R3G6',
  );
}
